from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime

from ..episode.schema import Episode

SKILL_THRESHOLD = 2  # minimum completions to emit a candidate skill


@dataclass
class SkillCandidate:
    domain: str
    pattern_summary: str
    evidence_episode_ids: list[str]
    learned_at: datetime
    applicability: str


def distill_skills(episodes: list[Episode]) -> list[SkillCandidate]:
    """
    Rule: domain seen >= SKILL_THRESHOLD times with 'completed' status -> candidate skill.
    """
    domain_successes: dict[str, list[Episode]] = defaultdict(list)
    for ep in episodes:
        if ep.outcome.status == "completed":
            domain_successes[ep.task_domain].append(ep)

    candidates: list[SkillCandidate] = []
    for domain, eps in domain_successes.items():
        if len(eps) < SKILL_THRESHOLD:
            continue
        ids = [ep.episode_id for ep in eps]
        descriptions = "; ".join(dict.fromkeys(ep.task_description[:80] for ep in eps))
        candidates.append(
            SkillCandidate(
                domain=domain,
                pattern_summary=descriptions,
                evidence_episode_ids=ids,
                learned_at=max(ep.ended_at for ep in eps),
                applicability=(
                    f"Observed in {len(eps)} completed tasks in domain '{domain}'."
                ),
            )
        )
    return candidates


def distill_warnings(episodes: list[Episode], threshold: int = 2) -> list[str]:
    """
    Rule: domain seen >= threshold times with failure status -> warning string.
    """
    domain_failures: dict[str, list[Episode]] = defaultdict(list)
    for ep in episodes:
        if ep.outcome.status in ("failed", "partial", "escalated"):
            domain_failures[ep.task_domain].append(ep)

    warnings: list[str] = []
    for domain, eps in domain_failures.items():
        if len(eps) >= threshold:
            reasons = [
                ep.outcome.escalation_reason or ep.outcome.verification_summary or "unknown"
                for ep in eps
                if ep.outcome.escalation_reason or ep.outcome.verification_summary
            ]
            reason_note = f" ({'; '.join(dict.fromkeys(reasons[:3]))})" if reasons else ""
            warnings.append(
                f"Domain '{domain}' has {len(eps)} failure(s){reason_note}."
            )
    return warnings


def render_skills_md(candidates: list[SkillCandidate]) -> str:
    lines = [
        "# SKILLS\n\n",
        "_Auto-generated by the CL substrate. Evidence-based, not hand-written._\n",
    ]
    for c in sorted(candidates, key=lambda x: x.learned_at, reverse=True):
        lines.append(f"\n## {c.domain}\n\n")
        lines.append(f"**Learned:** {c.learned_at.date()}\n\n")
        lines.append(f"**Pattern:** {c.pattern_summary}\n\n")
        lines.append(f"**Applies to:** {c.applicability}\n\n")
        lines.append(f"**Evidence:** {', '.join(c.evidence_episode_ids[:5])}\n")
    return "".join(lines)
